### ISSUE TITLE
Minor UX-tweaks of settings pane

### ISSUE THREAD

**Issue by hebe** [aptoma/drpublish-imbo-app#35]
![image](https://cloud.githubusercontent.com/assets/364610/10512824/70dd114e-7343-11e5-96d0-29234378eeba.png)

vs

![image](https://cloud.githubusercontent.com/assets/364610/10512846/97ccc326-7343-11e5-8b70-cc76a4be0cff.png)

^^ If only one of these have content, hide the button.

**Comment by rexxars** [comment]
Solved in #36.
