### ISSUE TITLE
Improve sliders

### ISSUE THREAD

**Issue by hebe** [aptoma/drpublish-imbo-app#39]
We need to make the sliders more intuitive.

I'll try to make something like this:

![image](https://cloud.githubusercontent.com/assets/364610/10554087/9cc9ebb0-7460-11e5-9eb3-8360d5e5fe9d.png)

- Add +/- buttons to make it possible to fine tune settings (needs js-implementation as well)
- Add lines to annotate 0 - 25% - 50% - 75% - 100%
- Add visual representation of what the setting slider adjusts.

**Comment by kbrabrand** [comment]
Features described implemented in #55, #54 and #52.
