### ISSUE TITLE
Crop + rotation bug

### ISSUE THREAD

**Issue by kbrabrand** [aptoma/drpublish-imbo-app#53]
There is a bug when a rotated image is cropped.It seems that when rotating the image and then choosing a crop that covers a large part of the width of the image after cropping. The result after cropping is a blank 1x1 pixel image.

An example of an URL that gives this result: https://drp-imbo.vgc.no/users/vgnett/images/gkP8e17_Ymak.jpg?t[]=rotate:angle=90,bg=000000&t[]=crop:width=3659,height=1007,x=1205,y=1809&t[]=maxSize:width=552&publicKey=drp-test&accessToken=c407f5d17af8abb304a781ba1d9baa7bd6a90b04e00f0833c898e2271a4731e7

**Steps to reproduce**
1. Click to insert a landscape photo
2. Rotate the image 90 degrees
3. Select a crop area that goes across the full width of the image (as shown below)

![image](https://cloud.githubusercontent.com/assets/2884292/10591508/c1ba8e9a-76b6-11e5-900c-5c5e48cf6f0b.png)

**Comment by kbrabrand** [comment]
A thought: it could be that the selected are for the crop is wider than the image..

**Comment by rexxars** [comment]
I think there are multiple bugs involved here.

First thing to note: 
Original image is `5760x3480`
Rotated dimensions are `3480x5760`
Crop params are `width=3659,height=1007,x=1205,y=1809`

The width and height is within limits, but the X and Y coordinates are not correct. An `x` of 1205 would put the crop area outside the image.

Seems to be a bug in Imbo after the crop has been applied too, though. I'll look into that.

**Comment by rexxars** [comment]
Found the bug in Imbo, but it's sort of a follow-through bug caused by incorrect crop parameters. It works as expected when the image variations listener is disabled. Enabling it will cause Imbo to recompute the crop parameters because they should be applied on a smaller image. This doesn't work as expected because the crop parameters are incorrect.

I'm creating a pull request to Imbo that makes it more strict (validates the crop parameters).

**Comment by kbrabrand** [comment]
After the latest bugfix the crop params seem to be correct, but there is in fact a bug in Imbo when using crop and maxSize in combination. A separate ticket has been created.

**Comment by kbrabrand** [comment]
Works with latest version of imbo2.0.
